name: delivery_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.0
  dropdown_search: ^5.0.6
  easy_stepper: ^0.8.3
  firebase_core: ^2.25.3
  firebase_messaging: ^14.7.14
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.7.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  image_picker: ^1.0.7
  image_pickers: ^2.0.4+8
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  introduction_screen: ^3.1.12
  jiffy: ^6.2.2
  lottie: ^2.7.0
  path: ^1.8.3
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 700
